name: "pulse"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    env_file:
      - ../.env

    command: sleep infinity

    networks:
      - default
      - shared-nats

networks:
  shared-nats:
    external: true
